<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\BloodGroup;
use App\Models\Country;
use App\Models\Governorate;
use App\Models\City;
use App\Models\Religion;
use App\Models\Qualification;
use App\Models\Resignation;
use App\Models\JobsCategory;
use App\Models\Department;
use App\Models\Nationality;
use App\Models\ShiftsType;
use App\Models\Branche;
use App\Models\MilitaryStatus;
use App\Models\DrivingLicenseType;
use App\Models\Language;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        // ===================== تنظيف البيانات المتعارضة لمنع الأخطاء =====================
        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
        
        $testEmails = [
            'ahmed.mohamed@elnour.com', 'sara.mahmoud@elnour.com', 'mohamed.khaled@elnour.com',
            'nasma.ahmed@elnour.com', 'khaled.hassan@elnour.com', 'fatma.mahmoud@elnour.com',
            'amr.sameh@elnour.com', 'mona.samir@elnour.com', 'tarek.abdullah@elnour.com',
            'heba.mohamed@elnour.com'
        ];
        $testCodes = [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010];
        $testFingerprints = ['FP1001', 'FP1002', 'FP1003', 'FP1004', 'FP1005', 'FP1006', 'FP1007', 'FP1008', 'FP1009', 'FP1010'];

        // Delete related admins
        \App\Models\Admin::where('is_employee', 1)
            ->where(function($query) use ($testEmails, $testCodes) {
                $query->whereIn('email', $testEmails)
                    ->orWhereIn('username', ['ahmed', 'sara', 'mohamed', 'nasma', 'khaled', 'fatma', 'amr', 'mona', 'tarek', 'heba']);
            })->delete();

        // Delete conflicting employees
        Employee::whereIn('email', $testEmails)
            ->orWhereIn('employee_code', $testCodes)
            ->orWhereIn('fingerprint_code', $testFingerprints)
            ->delete();

        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();

        // ===================== جلب الـ IDs من الجداول المرتبطة =====================

        $bloodGroups = BloodGroup::where('company_id', 1)->pluck('id', 'name')->toArray();
        $countries = Country::where('company_id', 1)->pluck('id', 'name')->toArray();
        $governorates = Governorate::where('company_id', 1)->pluck('id', 'name')->toArray();
        $cities = City::where('company_id', 1)->pluck('id', 'name')->toArray();
        $religions = Religion::where('company_id', 1)->pluck('id', 'name')->toArray();
        $qualifications = Qualification::where('company_id', 1)->pluck('id', 'name')->toArray();
        $jobs = JobsCategory::where('company_id', 1)->pluck('id', 'name')->toArray();
        $departments = Department::where('company_id', 1)->pluck('id', 'name')->toArray();
        $nationalities = Nationality::where('company_id', 1)->pluck('id', 'name')->toArray();
        $shiftTypes = ShiftsType::where('company_id', 1)->pluck('id')->toArray();
        $branches = Branche::where('company_id', 1)->pluck('id', 'name')->toArray();
        $militaryStatuses = MilitaryStatus::where('company_id', 1)->pluck('id', 'name')->toArray();
        $drivingLicenseTypes = DrivingLicenseType::where('company_id', 1)->pluck('id', 'name')->toArray();
        $languages = Language::where('company_id', 1)->pluck('id', 'name')->toArray();

        // ===================== بيانات الموظفين (10 موظفين) =====================

        $employees = [
            // ===================== الموظف 1: أحمد محمد علي =====================
            [
                'employee_code' => 1001,
                'fingerprint_code' => 'FP1001',
                'name' => 'أحمد محمد علي',
                'birth_date' => '1985-05-15',
                'email' => 'ahmed.mohamed@elnour.com',
                'home_telephone' => '0223456789',
                'work_telephone' => '0223456790',
                'blood_group_id' => $bloodGroups['O+'] ?? null,
                'stable_address' => 'شارع النيل، مدينة نصر، القاهرة',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['القاهرة'] ?? null,
                'city_id' => $cities['القاهرة'] ?? null,
                'home_address' => 'شارع النيل، مدينة نصر، القاهرة',
                'children_count' => 2,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => $militaryStatuses['تم الأداء'] ?? null,
                'military_start_date' => '2006-01-10',
                'military_end_date' => '2008-01-10',
                'military_weapon' => 'سلاح مشاة',
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 1,
                'driving_license_number' => 'DL123456',
                'driving_license_type_id' => $drivingLicenseTypes['سيارة خاصة'] ?? null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس طب وجراحة'] ?? null,
                'qualification_year' => '2008',
                'graduation_grade' => 2,
                'graduation_specialization' => 'جراحة عامة',
                'hire_date' => '2010-01-15',
                'hire_date_day_month_year' => '2010-01-15',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 1,
                'motivation_amount' => 1000.00,
                'payment_method' => 2,
                'bank_account_number' => 'EG123456789012345',
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 1,
                'relative_description' => 'والده تعمل بنفس المستشفى',
                'urgent_contact_details' => 'محمد أحمد - 01234567890',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الاطباء'] ?? null,
                'department_id' => $departments['قسم الجراحة العامة'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '12345678901234',
                'nationality_expiry_date' => '2030-12-31',
                'nationality_place_of_issue' => 'القاهرة',
                'sponsor_name' => null,
                'passport_number' => 'A12345678',
                'passport_expiry_date' => '2028-05-15',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/ahmed.jpg',
                'cv' => 'employees/cv/ahmed.pdf',
                'salary' => 15000.00,
                'language_id' => $languages['العربية'] ?? null,
                'fixed_shift' => 1,
                'shift_type_id' => $shiftTypes[0] ?? null,
                'payment_per_day' => 500.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1500.00,
                'social_insurance_number' => 'SI123456',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI123456',
                'medical_insurance_amount' => 500.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? null,
                'notes' => 'موظف متميز في قسم الجراحة العامة',
            ],

            // ===================== الموظف 2: سارة محمود إبراهيم =====================
            [
                'employee_code' => 1002,
                'fingerprint_code' => 'FP1002',
                'name' => 'سارة محمود إبراهيم',
                'birth_date' => '1990-08-22',
                'email' => 'sara.mahmoud@elnour.com',
                'home_telephone' => '0223456791',
                'work_telephone' => '0223456792',
                'blood_group_id' => $bloodGroups['A+'] ?? null,
                'stable_address' => 'شارع الهرم، الجيزة',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['الجيزة'] ?? null,
                'city_id' => $cities['الجيزة'] ?? null,
                'home_address' => 'شارع الهرم، الجيزة',
                'children_count' => 1,
                'gender' => 2,
                'marital_status' => 2,
                'military_status' => null,
                'military_start_date' => null,
                'military_end_date' => null,
                'military_weapon' => null,
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 1,
                'driving_license_number' => 'DL789012',
                'driving_license_type_id' => $drivingLicenseTypes['سيارة خاصة'] ?? null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس أشعة'] ?? null,
                'qualification_year' => '2012',
                'graduation_grade' => 1,
                'graduation_specialization' => 'الأشعة التشخيصية',
                'hire_date' => '2013-03-20',
                'hire_date_day_month_year' => '2013-03-20',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 2,
                'motivation_amount' => 800.00,
                'payment_method' => 2,
                'bank_account_number' => 'EG223456789012345',
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'إبراهيم محمود - 01123456789',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الاطباء'] ?? null,
                'department_id' => $departments['قسم الأشعة'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '22345678901234',
                'nationality_expiry_date' => '2032-08-22',
                'nationality_place_of_issue' => 'الجيزة',
                'sponsor_name' => null,
                'passport_number' => 'B23456789',
                'passport_expiry_date' => '2029-08-22',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/sara.jpg',
                'cv' => 'employees/cv/sara.pdf',
                'salary' => 12000.00,
                'language_id' => $languages['الإنجليزية'] ?? null,
                'fixed_shift' => 1,
                'shift_type_id' => $shiftTypes[0] ?? null,
                'payment_per_day' => 400.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1200.00,
                'social_insurance_number' => 'SI234567',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI234567',
                'medical_insurance_amount' => 400.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? null,
                'notes' => 'أخصائي أشعة ممتاز',
            ],

            // ===================== الموظف 3: محمد خالد عبدالله =====================
            [
                'employee_code' => 1003,
                'fingerprint_code' => 'FP1003',
                'name' => 'محمد خالد عبدالله',
                'birth_date' => '1982-11-10',
                'email' => 'mohamed.khaled@elnour.com',
                'home_telephone' => '0223456793',
                'work_telephone' => '0223456794',
                'blood_group_id' => $bloodGroups['B+'] ?? null,
                'stable_address' => 'شارع سموحة، الإسكندرية',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['الإسكندرية'] ?? null,
                'city_id' => $cities['الإسكندرية'] ?? null,
                'home_address' => 'شارع سموحة، الإسكندرية',
                'children_count' => 3,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => $militaryStatuses['تم الأداء'] ?? null,
                'military_start_date' => '2003-03-01',
                'military_end_date' => '2005-03-01',
                'military_weapon' => 'سلاح مدفعية',
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 1,
                'driving_license_number' => 'DL345678',
                'driving_license_type_id' => $drivingLicenseTypes['نقل خفيف'] ?? null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس طب وجراحة'] ?? null,
                'qualification_year' => '2006',
                'graduation_grade' => 2,
                'graduation_specialization' => 'جراحة العظام',
                'hire_date' => '2008-06-01',
                'hire_date_day_month_year' => '2008-06-01',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 1,
                'motivation_amount' => 1500.00,
                'payment_method' => 1,
                'bank_account_number' => null,
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'خالد عبدالله - 01234567891',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الاطباء'] ?? null,
                'department_id' => $departments['قسم العظام'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '32345678901234',
                'nationality_expiry_date' => '2031-11-10',
                'nationality_place_of_issue' => 'الإسكندرية',
                'sponsor_name' => null,
                'passport_number' => 'C34567890',
                'passport_expiry_date' => '2027-11-10',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/mohamed.jpg',
                'cv' => 'employees/cv/mohamed.pdf',
                'salary' => 18000.00,
                'language_id' => $languages['العربية'] ?? null,
                'fixed_shift' => 1,
                'shift_type_id' => $shiftTypes[0] ?? null,
                'payment_per_day' => 600.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1800.00,
                'social_insurance_number' => 'SI345678',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI345678',
                'medical_insurance_amount' => 600.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? null,
                'notes' => 'أستاذ جراحة العظام',
            ],

            // ===================== الموظف 4: نسمة أحمد سعيد =====================
            [
                'employee_code' => 1004,
                'fingerprint_code' => 'FP1004',
                'name' => 'نسمة أحمد سعيد',
                'birth_date' => '1995-03-05',
                'email' => 'nasma.ahmed@elnour.com',
                'home_telephone' => '0223456795',
                'work_telephone' => '0223456796',
                'blood_group_id' => $bloodGroups['AB+'] ?? null,
                'stable_address' => 'شارع البحر، دمياط',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['دمياط'] ?? null,
                'city_id' => $cities['دمياط'] ?? null,
                'home_address' => 'شارع البحر، دمياط',
                'children_count' => 0,
                'gender' => 2,
                'marital_status' => 1,
                'military_status' => null,
                'military_start_date' => null,
                'military_end_date' => null,
                'military_weapon' => null,
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 0,
                'driving_license_number' => null,
                'driving_license_type_id' => null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس طب وجراحة'] ?? null,
                'qualification_year' => '2017',
                'graduation_grade' => 1,
                'graduation_specialization' => 'طب الأطفال',
                'hire_date' => '2018-09-10',
                'hire_date_day_month_year' => '2018-09-10',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 0,
                'motivation_amount' => 0.00,
                'payment_method' => 2,
                'bank_account_number' => 'EG423456789012345',
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'أحمد سعيد - 01234567893',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الاطباء'] ?? null,
                'department_id' => $departments['قسم الأطفال'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '42345678901234',
                'nationality_expiry_date' => '2033-03-05',
                'nationality_place_of_issue' => 'دمياط',
                'sponsor_name' => null,
                'passport_number' => 'D45678901',
                'passport_expiry_date' => '2030-03-05',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/nasma.jpg',
                'cv' => 'employees/cv/nasma.pdf',
                'salary' => 10000.00,
                'language_id' => $languages['الإنجليزية'] ?? null,
                'fixed_shift' => 0,
                'shift_type_id' => null,
                'payment_per_day' => 330.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1000.00,
                'social_insurance_number' => 'SI456789',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI456789',
                'medical_insurance_amount' => 300.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['فرع دمياط'] ?? null,
                'notes' => 'طبية أطفال متميزة',
            ],

            // ===================== الموظف 5: خالد حسن يوسف =====================
            [
                'employee_code' => 1005,
                'fingerprint_code' => 'FP1005',
                'name' => 'خالد حسن يوسف',
                'birth_date' => '1988-07-18',
                'email' => 'khaled.hassan@elnour.com',
                'home_telephone' => '0223456797',
                'work_telephone' => '0223456798',
                'blood_group_id' => $bloodGroups['A-'] ?? null,
                'stable_address' => 'شارع الجامع، المنصورة',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['الدقهلية'] ?? null,
                'city_id' => $cities['المنصورة'] ?? null,
                'home_address' => 'شارع الجامع، المنصورة',
                'children_count' => 2,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => $militaryStatuses['تم الأداء'] ?? null,
                'military_start_date' => '2008-07-15',
                'military_end_date' => '2010-07-15',
                'military_weapon' => 'سلاح مشاة',
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 1,
                'driving_license_number' => 'DL901234',
                'driving_license_type_id' => $drivingLicenseTypes['سيارة خاصة'] ?? null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس صيدلة'] ?? null,
                'qualification_year' => '2010',
                'graduation_grade' => 3,
                'graduation_specialization' => 'الصيدلة الإكلينيكية',
                'hire_date' => '2011-11-15',
                'hire_date_day_month_year' => '2011-11-15',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 1,
                'motivation_amount' => 500.00,
                'payment_method' => 2,
                'bank_account_number' => 'EG523456789012345',
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'حسن يوسف - 01234567894',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الصيادلة'] ?? null,
                'department_id' => $departments['قسم الصيدلة'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '52345678901234',
                'nationality_expiry_date' => '2032-07-18',
                'nationality_place_of_issue' => 'المنصورة',
                'sponsor_name' => null,
                'passport_number' => 'E56789012',
                'passport_expiry_date' => '2028-07-18',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/khaled.jpg',
                'cv' => 'employees/cv/khaled.pdf',
                'salary' => 13000.00,
                'language_id' => $languages['العربية'] ?? null,
                'fixed_shift' => 1,
                'shift_type_id' => $shiftTypes[0] ?? null,
                'payment_per_day' => 430.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1300.00,
                'social_insurance_number' => 'SI567890',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI567890',
                'medical_insurance_amount' => 450.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? null,
                'notes' => 'صيدلي أول',
            ],

            // ===================== الموظف 6: فاطمة محمود رضا =====================
            [
                'employee_code' => 1006,
                'fingerprint_code' => 'FP1006',
                'name' => 'فاطمة محمود رضا',
                'birth_date' => '1992-12-25',
                'email' => 'fatma.mahmoud@elnour.com',
                'home_telephone' => '0223456799',
                'work_telephone' => '0223456800',
                'blood_group_id' => $bloodGroups['AB-'] ?? null,
                'stable_address' => 'شارع المدارس، طنطا',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['الغربية'] ?? null,
                'city_id' => $cities['طنطا'] ?? null,
                'home_address' => 'شارع المدارس، طنطا',
                'children_count' => 1,
                'gender' => 2,
                'marital_status' => 2,
                'military_status' => null,
                'military_start_date' => null,
                'military_end_date' => null,
                'military_weapon' => null,
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 0,
                'driving_license_number' => null,
                'driving_license_type_id' => null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس تمريض'] ?? null,
                'qualification_year' => '2014',
                'graduation_grade' => 2,
                'graduation_specialization' => 'التخدير',
                'hire_date' => '2015-04-20',
                'hire_date_day_month_year' => '2015-04-20',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 0,
                'motivation_amount' => 0.00,
                'payment_method' => 1,
                'bank_account_number' => null,
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 1,
                'relative_description' => 'أختها تعمل بالقسم نفسه',
                'urgent_contact_details' => 'محمود رضا - 01234567895',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['التمريض'] ?? null,
                'department_id' => $departments['قسم التخدير'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '62345678901234',
                'nationality_expiry_date' => '2034-12-25',
                'nationality_place_of_issue' => 'طنطا',
                'sponsor_name' => null,
                'passport_number' => 'F67890123',
                'passport_expiry_date' => '2029-12-25',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/fatma.jpg',
                'cv' => 'employees/cv/fatma.pdf',
                'salary' => 11000.00,
                'language_id' => $languages['العربية'] ?? null,
                'fixed_shift' => 0,
                'shift_type_id' => null,
                'payment_per_day' => 370.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1100.00,
                'social_insurance_number' => 'SI678901',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI678901',
                'medical_insurance_amount' => 350.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? null,
                'notes' => 'ممرضة تخدير ماهرة',
            ],

            // ===================== الموظف 7: عمرو سامح إبراهيم =====================
            [
                'employee_code' => 1007,
                'fingerprint_code' => 'FP1007',
                'name' => 'عمرو سامح إبراهيم',
                'birth_date' => '1980-09-30',
                'email' => 'amr.sameh@elnour.com',
                'home_telephone' => '0223456801',
                'work_telephone' => '0223456802',
                'blood_group_id' => $bloodGroups['B-'] ?? null,
                'stable_address' => 'شارع النجاح، أسيوط',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['أسيوط'] ?? null,
                'city_id' => $cities['أسيوط'] ?? null,
                'home_address' => 'شارع النجاح، أسيوط',
                'children_count' => 3,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => $militaryStatuses['تم الأداء'] ?? null,
                'military_start_date' => '2001-10-01',
                'military_end_date' => '2003-10-01',
                'military_weapon' => 'سلاح مدرعات',
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 1,
                'driving_license_number' => 'DL123789',
                'driving_license_type_id' => $drivingLicenseTypes['نقل ثقيل'] ?? null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس طب وجراحة'] ?? null,
                'qualification_year' => '2004',
                'graduation_grade' => 2,
                'graduation_specialization' => 'جراحة القلب',
                'hire_date' => '2006-08-01',
                'hire_date_day_month_year' => '2006-08-01',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 2,
                'motivation_amount' => 2000.00,
                'payment_method' => 2,
                'bank_account_number' => 'EG723456789012345',
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'سامح إبراهيم - 01234567896',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الاطباء'] ?? null,
                'department_id' => $departments['قسم القلب'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '72345678901234',
                'nationality_expiry_date' => '2031-09-30',
                'nationality_place_of_issue' => 'أسيوط',
                'sponsor_name' => null,
                'passport_number' => 'G78901234',
                'passport_expiry_date' => '2027-09-30',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/amr.jpg',
                'cv' => 'employees/cv/amr.pdf',
                'salary' => 20000.00,
                'language_id' => $languages['الإنجليزية'] ?? null,
                'fixed_shift' => 1,
                'shift_type_id' => $shiftTypes[0] ?? null,
                'payment_per_day' => 670.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 2000.00,
                'social_insurance_number' => 'SI789012',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI789012',
                'medical_insurance_amount' => 700.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? null,
                'notes' => 'استشاري جراحة القلب المفتوح',
            ],

            // ===================== الموظف 8: منى سمير رشاد =====================
            [
                'employee_code' => 1008,
                'fingerprint_code' => 'FP1008',
                'name' => 'منى سمير رشاد',
                'birth_date' => '1993-06-12',
                'email' => 'mona.samir@elnour.com',
                'home_telephone' => '0223456803',
                'work_telephone' => '0223456804',
                'blood_group_id' => $bloodGroups['O-'] ?? null,
                'stable_address' => 'شارع الجمهورية، بني سويف',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['بني سويف'] ?? null,
                'city_id' => $cities['بني سويف'] ?? null,
                'home_address' => 'شارع الجمهورية، بني سويف',
                'children_count' => 0,
                'gender' => 2,
                'marital_status' => 1,
                'military_status' => null,
                'military_start_date' => null,
                'military_end_date' => null,
                'military_weapon' => null,
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 1,
                'driving_license_number' => 'DL456123',
                'driving_license_type_id' => $drivingLicenseTypes['سيارة خاصة'] ?? null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس مختبرات'] ?? null,
                'qualification_year' => '2015',
                'graduation_grade' => 1,
                'graduation_specialization' => 'التحاليل الطبية',
                'hire_date' => '2016-10-10',
                'hire_date_day_month_year' => '2016-10-10',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 0,
                'motivation_amount' => 0.00,
                'payment_method' => 2,
                'bank_account_number' => 'EG823456789012345',
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'سمير رشاد - 01234567897',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الفنيين'] ?? null,
                'department_id' => $departments['قسم المختبر'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '82345678901234',
                'nationality_expiry_date' => '2033-06-12',
                'nationality_place_of_issue' => 'بني سويف',
                'sponsor_name' => null,
                'passport_number' => 'H89012345',
                'passport_expiry_date' => '2030-06-12',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/mona.jpg',
                'cv' => 'employees/cv/mona.pdf',
                'salary' => 9500.00,
                'language_id' => $languages['العربية'] ?? null,
                'fixed_shift' => 0,
                'shift_type_id' => null,
                'payment_per_day' => 320.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 950.00,
                'social_insurance_number' => 'SI890123',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI890123',
                'medical_insurance_amount' => 280.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? null,
                'notes' => 'اخصائي تحاليل طبية',
            ],

            // ===================== الموظف 9: طارق عبدالله محمود =====================
            [
                'employee_code' => 1009,
                'fingerprint_code' => 'FP1009',
                'name' => 'طارق عبدالله محمود',
                'birth_date' => '1987-02-28',
                'email' => 'tarek.abdullah@elnour.com',
                'home_telephone' => '0223456805',
                'work_telephone' => '0223456806',
                'blood_group_id' => $bloodGroups['A+'] ?? null,
                'stable_address' => 'شارع الكورنيش، الأقصر',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['الأقصر'] ?? null,
                'city_id' => $cities['الأقصر'] ?? null,
                'home_address' => 'شارع الكورنيش، الأقصر',
                'children_count' => 2,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => $militaryStatuses['تم الأداء'] ?? null,
                'military_start_date' => '2007-03-20',
                'military_end_date' => '2009-03-20',
                'military_weapon' => 'سلاح مشاة',
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 1,
                'driving_license_number' => 'DL789456',
                'driving_license_type_id' => $drivingLicenseTypes['سيارة خاصة'] ?? null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس أسنان'] ?? null,
                'qualification_year' => '2009',
                'graduation_grade' => 3,
                'graduation_specialization' => 'جراحة الفم والأسنان',
                'hire_date' => '2010-12-01',
                'hire_date_day_month_year' => '2010-12-01',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 1,
                'motivation_amount' => 750.00,
                'payment_method' => 1,
                'bank_account_number' => null,
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'عبدالله محمود - 01234567898',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['الاطباء'] ?? null,
                'department_id' => $departments['قسم الأسنان'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '92345678901234',
                'nationality_expiry_date' => '2032-02-28',
                'nationality_place_of_issue' => 'الأقصر',
                'sponsor_name' => null,
                'passport_number' => 'I90123456',
                'passport_expiry_date' => '2028-02-28',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/tarek.jpg',
                'cv' => 'employees/cv/tarek.pdf',
                'salary' => 14000.00,
                'language_id' => $languages['العربية'] ?? null,
                'fixed_shift' => 1,
                'shift_type_id' => $shiftTypes[0] ?? null,
                'payment_per_day' => 470.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1400.00,
                'social_insurance_number' => 'SI901234',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI901234',
                'medical_insurance_amount' => 480.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['فرع الأقصر'] ?? null,
                'notes' => 'طبيب أسنان ممتاز',
            ],

            // ===================== الموظف 10: هبة الله محمد فريد =====================
            [
                'employee_code' => 1010,
                'fingerprint_code' => 'FP1010',
                'name' => 'هبة الله محمد فريد',
                'birth_date' => '1991-04-17',
                'email' => 'heba.mohamed@elnour.com',
                'home_telephone' => '0223456807',
                'work_telephone' => '0223456808',
                'blood_group_id' => $bloodGroups['B+'] ?? null,
                'stable_address' => 'شارع النصر، بورسعيد',
                'country_id' => $countries['مصر'] ?? null,
                'governorate_id' => $governorates['بورسعيد'] ?? null,
                'city_id' => $cities['بورسعيد'] ?? null,
                'home_address' => 'شارع النصر، بورسعيد',
                'children_count' => 1,
                'gender' => 2,
                'marital_status' => 2,
                'military_status' => null,
                'military_start_date' => null,
                'military_end_date' => null,
                'military_weapon' => null,
                'military_exemption_date' => null,
                'military_exemption_reason' => null,
                'postponement_reason' => null,
                'driving_license' => 0,
                'driving_license_number' => null,
                'driving_license_type_id' => null,
                'religion_id' => $religions['الإسلام'] ?? null,
                'qualifications_id' => $qualifications['بكالوريوس تمريض'] ?? null,
                'qualification_year' => '2013',
                'graduation_grade' => 2,
                'graduation_specialization' => 'التمريض العام',
                'hire_date' => '2014-07-15',
                'hire_date_day_month_year' => '2014-07-15',
                'employment_status' => 1,
                'resignation_id' => null,
                'resignation_date' => null,
                'resignation_reason' => null,
                'motivation_type' => 1,
                'motivation_amount' => 300.00,
                'payment_method' => 1,
                'bank_account_number' => null,
                'has_disability' => 0,
                'disability_description' => null,
                'has_relative' => 0,
                'relative_description' => null,
                'urgent_contact_details' => 'محمد فريد - 01234567899',
                'daily_work_hours' => 8.00,
                'job_id' => $jobs['التمريض'] ?? null,
                'department_id' => $departments['قسم العناية المركزة'] ?? null,
                'nationality_id' => $nationalities['مصري'] ?? null,
                'nationality_number' => '02345678901234',
                'nationality_expiry_date' => '2034-04-17',
                'nationality_place_of_issue' => 'بورسعيد',
                'sponsor_name' => null,
                'passport_number' => 'J01234567',
                'passport_expiry_date' => '2029-04-17',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'image' => 'employees/profile/heba.jpg',
                'cv' => 'employees/cv/heba.pdf',
                'salary' => 8500.00,
                'language_id' => $languages['العربية'] ?? null,
                'fixed_shift' => 0,
                'shift_type_id' => null,
                'payment_per_day' => 280.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 850.00,
                'social_insurance_number' => 'SI012345',
                'has_medical_insurance' => 1,
                'medical_insurance_number' => 'MI012345',
                'medical_insurance_amount' => 250.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'vacation_formula' => 0,
                'active_for_vacation' => 1,
                'has_sensitive_data' => 0,
                'branch_id' => $branches['فرع بورسعيد'] ?? null,
                'notes' => 'ممرضة مجتهدة في العناية المركزة',
            ],
        ];

        // ===================== إدراج البيانات في قاعدة البيانات =====================

        foreach ($employees as $employee) {
            $employee['added_by'] = 1;
            $employee['updated_by'] = 1;
            $empRecord = Employee::updateOrCreate(
                ['employee_code' => $employee['employee_code'], 'company_id' => 1],
                $employee
            );

            // Create admin login account for some employees (e.g. Ahmed and Sara)
            if (in_array($empRecord->employee_code, [1001, 1002])) {
                $username = $empRecord->employee_code == 1001 ? 'ahmed' : 'sara';
                \App\Models\Admin::updateOrCreate(
                    ['email' => $empRecord->email],
                    [
                        'name' => $empRecord->name,
                        'username' => $username,
                        'password' => \Illuminate\Support\Facades\Hash::make('password123'),
                        'status' => 1,
                        'date' => date('Y-m-d H:i:s'),
                        'company_id' => 1,
                        'added_by' => 1,
                        'updated_by' => 1,
                        'is_master_admin' => 0,
                        'is_employee' => 1,
                        'employee_id' => $empRecord->id,
                        'allow_login' => 1,
                        'permission_role_id' => null,
                    ]
                );
            }
        }

        $this->command->info('✅ Employees seeded: ' . count($employees) . ' records');
    }
}
