<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\BloodGroup;
use App\Models\Country;
use App\Models\Governorate;
use App\Models\City;
use App\Models\Religion;
use App\Models\Qualification;
use App\Models\Resignation;
use App\Models\JobsCategory;
use App\Models\Department;
use App\Models\Nationality;
use App\Models\ShiftsType;
use App\Models\Branche;
use App\Models\DrivingLicenseType;
use App\Models\MilitaryStatus;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'employee_code' => 1001,
                'fingerprint_code' => 'FP1001',
                'name' => 'أحمد محمد علي',
                'birth_date' => '1985-05-15',
                'email' => 'ahmed.mohamed@elnour.com',
                'home_telephone' => '0223456789',
                'work_telephone' => '0223456790',
                'stable_address' => 'شارع النيل، مدينة نصر، القاهرة',
                'children_count' => 2,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => 1,
                'driving_license' => 1,
                'driving_license_number' => 'DL123456',
                'qualification_year' => '2008',
                'graduation_grade' => 2,
                'graduation_specialization' => 'جراحة عامة',
                'hire_date' => '2010-01-15',
                'hire_date_day_month_year' => '2010-01-15',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '12345678901234',
                'nationality_expiry_date' => '2030-12-31',
                'nationality_place_of_issue' => 'القاهرة',
                'passport_number' => 'A12345678',
                'passport_expiry_date' => '2028-05-15',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 15000.00,
                'payment_per_day' => 500.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1500.00,
                'social_insurance_number' => 'SI123456',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 500.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'fixed_shift' => 1,
            ],
            [
                'employee_code' => 1002,
                'fingerprint_code' => 'FP1002',
                'name' => 'سارة محمود إبراهيم',
                'birth_date' => '1990-08-22',
                'email' => 'sara.mahmoud@elnour.com',
                'home_telephone' => '0223456791',
                'work_telephone' => '0223456792',
                'stable_address' => 'شارع الهرم، الجيزة',
                'children_count' => 1,
                'gender' => 2,
                'marital_status' => 2,
                'driving_license' => 1,
                'driving_license_number' => 'DL789012',
                'qualification_year' => '2012',
                'graduation_grade' => 1,
                'graduation_specialization' => 'الأشعة التشخيصية',
                'hire_date' => '2013-03-20',
                'hire_date_day_month_year' => '2013-03-20',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '22345678901234',
                'nationality_expiry_date' => '2032-08-22',
                'nationality_place_of_issue' => 'الجيزة',
                'passport_number' => 'B23456789',
                'passport_expiry_date' => '2029-08-22',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 12000.00,
                'payment_per_day' => 400.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1200.00,
                'social_insurance_number' => 'SI234567',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 400.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'fixed_shift' => 1,
            ],
            [
                'employee_code' => 1003,
                'fingerprint_code' => 'FP1003',
                'name' => 'محمد خالد عبدالله',
                'birth_date' => '1982-11-10',
                'email' => 'mohamed.khaled@elnour.com',
                'home_telephone' => '0223456793',
                'work_telephone' => '0223456794',
                'stable_address' => 'شارع سموحة، الإسكندرية',
                'children_count' => 3,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => 1,
                'driving_license' => 1,
                'driving_license_number' => 'DL345678',
                'qualification_year' => '2006',
                'graduation_grade' => 2,
                'graduation_specialization' => 'جراحة العظام',
                'hire_date' => '2008-06-01',
                'hire_date_day_month_year' => '2008-06-01',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '32345678901234',
                'nationality_expiry_date' => '2031-11-10',
                'nationality_place_of_issue' => 'الإسكندرية',
                'passport_number' => 'C34567890',
                'passport_expiry_date' => '2027-11-10',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 18000.00,
                'payment_per_day' => 600.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1800.00,
                'social_insurance_number' => 'SI345678',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 600.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'fixed_shift' => 1,
            ],
            [
                'employee_code' => 1004,
                'fingerprint_code' => 'FP1004',
                'name' => 'نسمة أحمد سعيد',
                'birth_date' => '1995-03-05',
                'email' => 'nasma.ahmed@elnour.com',
                'home_telephone' => '0223456795',
                'work_telephone' => '0223456796',
                'stable_address' => 'شارع البحر، دمياط',
                'children_count' => 0,
                'gender' => 2,
                'marital_status' => 1,
                'driving_license' => 0,
                'qualification_year' => '2017',
                'graduation_grade' => 1,
                'graduation_specialization' => 'طب الأطفال',
                'hire_date' => '2018-09-10',
                'hire_date_day_month_year' => '2018-09-10',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '42345678901234',
                'nationality_expiry_date' => '2033-03-05',
                'nationality_place_of_issue' => 'دمياط',
                'passport_number' => 'D45678901',
                'passport_expiry_date' => '2030-03-05',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 10000.00,
                'payment_per_day' => 330.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1000.00,
                'social_insurance_number' => 'SI456789',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 300.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'fixed_shift' => 0,
            ],
            [
                'employee_code' => 1005,
                'fingerprint_code' => 'FP1005',
                'name' => 'خالد حسن يوسف',
                'birth_date' => '1988-07-18',
                'email' => 'khaled.hassan@elnour.com',
                'home_telephone' => '0223456797',
                'work_telephone' => '0223456798',
                'stable_address' => 'شارع الجامع، المنصورة',
                'children_count' => 2,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => 1,
                'driving_license' => 1,
                'driving_license_number' => 'DL901234',
                'qualification_year' => '2010',
                'graduation_grade' => 3,
                'graduation_specialization' => 'الصيدلة الإكلينيكية',
                'hire_date' => '2011-11-15',
                'hire_date_day_month_year' => '2011-11-15',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '52345678901234',
                'nationality_expiry_date' => '2032-07-18',
                'nationality_place_of_issue' => 'المنصورة',
                'passport_number' => 'E56789012',
                'passport_expiry_date' => '2028-07-18',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 13000.00,
                'payment_per_day' => 430.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1300.00,
                'social_insurance_number' => 'SI567890',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 450.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'fixed_shift' => 1,
            ],
            [
                'employee_code' => 1006,
                'fingerprint_code' => 'FP1006',
                'name' => 'فاطمة محمود رضا',
                'birth_date' => '1992-12-25',
                'email' => 'fatma.mahmoud@elnour.com',
                'home_telephone' => '0223456799',
                'work_telephone' => '0223456800',
                'stable_address' => 'شارع المدارس، طنطا',
                'children_count' => 1,
                'gender' => 2,
                'marital_status' => 2,
                'driving_license' => 0,
                'qualification_year' => '2014',
                'graduation_grade' => 2,
                'graduation_specialization' => 'التخدير',
                'hire_date' => '2015-04-20',
                'hire_date_day_month_year' => '2015-04-20',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '62345678901234',
                'nationality_expiry_date' => '2034-12-25',
                'nationality_place_of_issue' => 'طنطا',
                'passport_number' => 'F67890123',
                'passport_expiry_date' => '2029-12-25',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 11000.00,
                'payment_per_day' => 370.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1100.00,
                'social_insurance_number' => 'SI678901',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 350.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'fixed_shift' => 0,
            ],
            [
                'employee_code' => 1007,
                'fingerprint_code' => 'FP1007',
                'name' => 'عمرو سامح إبراهيم',
                'birth_date' => '1980-09-30',
                'email' => 'amr.sameh@elnour.com',
                'home_telephone' => '0223456801',
                'work_telephone' => '0223456802',
                'stable_address' => 'شارع النجاح، أسيوط',
                'children_count' => 3,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => 1,
                'driving_license' => 1,
                'driving_license_number' => 'DL123789',
                'qualification_year' => '2004',
                'graduation_grade' => 2,
                'graduation_specialization' => 'جراحة القلب',
                'hire_date' => '2006-08-01',
                'hire_date_day_month_year' => '2006-08-01',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '72345678901234',
                'nationality_expiry_date' => '2031-09-30',
                'nationality_place_of_issue' => 'أسيوط',
                'passport_number' => 'G78901234',
                'passport_expiry_date' => '2027-09-30',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 20000.00,
                'payment_per_day' => 670.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 2000.00,
                'social_insurance_number' => 'SI789012',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 700.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'fixed_shift' => 1,
            ],
            [
                'employee_code' => 1008,
                'fingerprint_code' => 'FP1008',
                'name' => 'منى سمير رشاد',
                'birth_date' => '1993-06-12',
                'email' => 'mona.samir@elnour.com',
                'home_telephone' => '0223456803',
                'work_telephone' => '0223456804',
                'stable_address' => 'شارع الجمهورية، بني سويف',
                'children_count' => 0,
                'gender' => 2,
                'marital_status' => 1,
                'driving_license' => 1,
                'driving_license_number' => 'DL456123',
                'qualification_year' => '2015',
                'graduation_grade' => 1,
                'graduation_specialization' => 'التحاليل الطبية',
                'hire_date' => '2016-10-10',
                'hire_date_day_month_year' => '2016-10-10',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '82345678901234',
                'nationality_expiry_date' => '2033-06-12',
                'nationality_place_of_issue' => 'بني سويف',
                'passport_number' => 'H89012345',
                'passport_expiry_date' => '2030-06-12',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 9500.00,
                'payment_per_day' => 320.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 950.00,
                'social_insurance_number' => 'SI890123',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 280.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'fixed_shift' => 0,
            ],
            [
                'employee_code' => 1009,
                'fingerprint_code' => 'FP1009',
                'name' => 'طارق عبدالله محمود',
                'birth_date' => '1987-02-28',
                'email' => 'tarek.abdullah@elnour.com',
                'home_telephone' => '0223456805',
                'work_telephone' => '0223456806',
                'stable_address' => 'شارع الكورنيش، الأقصر',
                'children_count' => 2,
                'gender' => 1,
                'marital_status' => 2,
                'military_status' => 1,
                'driving_license' => 1,
                'driving_license_number' => 'DL789456',
                'qualification_year' => '2009',
                'graduation_grade' => 3,
                'graduation_specialization' => 'جراحة الفم والأسنان',
                'hire_date' => '2010-12-01',
                'hire_date_day_month_year' => '2010-12-01',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '92345678901234',
                'nationality_expiry_date' => '2032-02-28',
                'nationality_place_of_issue' => 'الأقصر',
                'passport_number' => 'I90123456',
                'passport_expiry_date' => '2028-02-28',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 14000.00,
                'payment_per_day' => 470.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 1400.00,
                'social_insurance_number' => 'SI901234',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 480.00,
                'fixed_allowance' => 1,
                'has_attendance' => 1,
                'fixed_shift' => 1,
            ],
            [
                'employee_code' => 1010,
                'fingerprint_code' => 'FP1010',
                'name' => 'هبة الله محمد فريد',
                'birth_date' => '1991-04-17',
                'email' => 'heba.mohamed@elnour.com',
                'home_telephone' => '0223456807',
                'work_telephone' => '0223456808',
                'stable_address' => 'شارع النصر، بورسعيد',
                'children_count' => 1,
                'gender' => 2,
                'marital_status' => 2,
                'driving_license' => 0,
                'qualification_year' => '2013',
                'graduation_grade' => 2,
                'graduation_specialization' => 'التمريض',
                'hire_date' => '2014-07-15',
                'hire_date_day_month_year' => '2014-07-15',
                'employment_status' => 1,
                'daily_work_hours' => 8.00,
                'nationality_number' => '02345678901234',
                'nationality_expiry_date' => '2034-04-17',
                'nationality_place_of_issue' => 'بورسعيد',
                'passport_number' => 'J01234567',
                'passport_expiry_date' => '2029-04-17',
                'passport_place_of_issue' => 'مصلحة الجوازات',
                'salary' => 8500.00,
                'payment_per_day' => 280.00,
                'has_social_insurance' => 1,
                'social_insurance_amount' => 850.00,
                'social_insurance_number' => 'SI012345',
                'has_medical_insurance' => 1,
                'medical_insurance_amount' => 250.00,
                'fixed_allowance' => 0,
                'has_attendance' => 1,
                'fixed_shift' => 0,
            ],
        ];

        // جلب الـ IDs من الجداول المرتبطة
        $bloodGroups = BloodGroup::where('company_id', 1)->pluck('id', 'name')->toArray();
        $countries = Country::where('company_id', 1)->pluck('id', 'name')->toArray();
        $governorates = Governorate::where('company_id', 1)->pluck('id', 'name')->toArray();
        $cities = City::where('company_id', 1)->pluck('id', 'name')->toArray();
        $religions = Religion::where('company_id', 1)->pluck('id', 'name')->toArray();
        $qualifications = Qualification::where('company_id', 1)->pluck('id', 'name')->toArray();
        $jobs = JobsCategory::where('company_id', 1)->pluck('id', 'name')->toArray();
        $departments = Department::where('company_id', 1)->pluck('id', 'name')->toArray();
        $nationalities = Nationality::where('company_id', 1)->pluck('id', 'name')->toArray();
        $shifts = ShiftsType::where('company_id', 1)->pluck('id', 'type')->toArray();
        $branches = Branche::where('company_id', 1)->pluck('id', 'name')->toArray();
        $military_statuses = MilitaryStatus::where('company_id', 1)->pluck('id', 'name')->toArray();
        $driving_license_types = DrivingLicenseType::where('company_id', 1)->pluck('id', 'name')->toArray();

        foreach ($employees as $index => $employee) {
            Employee::updateOrCreate(
                ['employee_code' => $employee['employee_code'], 'company_id' => 1],
                [
                    'fingerprint_code' => $employee['fingerprint_code'],
                    'name' => $employee['name'],
                    'birth_date' => $employee['birth_date'],
                    'email' => $employee['email'],
                    'home_telephone' => $employee['home_telephone'],
                    'work_telephone' => $employee['work_telephone'],
                    'blood_group_id' => $bloodGroups['O+'] ?? null,
                    'stable_address' => $employee['stable_address'],
                    'country_id' => $countries['مصر'] ?? null,
                    'governorate_id' => $governorates[$employee['stable_address'] === 'شارع النيل، مدينة نصر، القاهرة' ? 'القاهرة' : ($employee['stable_address'] === 'شارع الهرم، الجيزة' ? 'الجيزة' : 'القاهرة')] ?? null,
                    'city_id' => $cities[$employee['stable_address'] === 'شارع النيل، مدينة نصر، القاهرة' ? 'القاهرة' : ($employee['stable_address'] === 'شارع الهرم، الجيزة' ? 'الجيزة' : 'القاهرة')] ?? null,
                    'children_count' => $employee['children_count'],
                    'gender' => $employee['gender'],
                    'marital_status' => $employee['marital_status'],
                    'military_status' =>  $employee['military_status'] ?? null,
                    'driving_license' => $employee['driving_license'],
                    'driving_license_number' => $employee['driving_license_number'] ?? null,
                    'driving_license_type_id' => $driving_license_types['سيارة خاصة'] ?? null,
                    'religion_id' => $religions['الإسلام'] ?? null,
                    'qualifications_id' => $qualifications['بكالوريوس طب وجراحة'] ?? null,
                    'qualification_year' => $employee['qualification_year'],
                    'graduation_grade' => $employee['graduation_grade'],
                    'graduation_specialization' => $employee['graduation_specialization'],
                    'hire_date' => $employee['hire_date'],
                    'hire_date_day_month_year' => $employee['hire_date_day_month_year'],
                    'employment_status' => $employee['employment_status'],
                    'daily_work_hours' => $employee['daily_work_hours'],
                    'job_id' => $jobs['الاطباء'] ?? 1,
                    'department_id' => $departments['قسم الجراحة العامة'] ?? 1,
                    'nationality_id' => $nationalities['مصري'] ?? 1,
                    'nationality_number' => $employee['nationality_number'],
                    'nationality_expiry_date' => $employee['nationality_expiry_date'],
                    'nationality_place_of_issue' => $employee['nationality_place_of_issue'],
                    'passport_number' => $employee['passport_number'],
                    'passport_expiry_date' => $employee['passport_expiry_date'],
                    'passport_place_of_issue' => $employee['passport_place_of_issue'],
                    'salary' => $employee['salary'],
                    'payment_per_day' => $employee['payment_per_day'],
                    'has_social_insurance' => $employee['has_social_insurance'],
                    'social_insurance_amount' => $employee['social_insurance_amount'],
                    'social_insurance_number' => $employee['social_insurance_number'],
                    'has_medical_insurance' => $employee['has_medical_insurance'],
                    'medical_insurance_amount' => $employee['medical_insurance_amount'],
                    'fixed_allowance' => $employee['fixed_allowance'],
                    'has_attendance' => $employee['has_attendance'],
                    'fixed_shift' => $employee['fixed_shift'],
                    'shift_type_id' => $employee['fixed_shift'] == 1 ? ($shifts[1] ?? null) : null,
                    'branch_id' => $branches['الفرع الرئيسي - مدينة نصر'] ?? 1,
                    'company_id' => 1,
                    'added_by' => 1,
                    'updated_by' => 1,
                ]
            );
        }

        $this->command->info('✅ Employees seeded: ' . count($employees) . ' records');
    }
}
